#!/usr/bin/env bash
#
# Post-installation Configuration Scripts
#
# Docker installation
# - Install packages to allow apt to use a repository over HTTPS
# - Add Docker’s official GPG key
# - Check if we have right fingerprint
# - Install stable repository
# - Install Docker CE


# Install packages to allow apt to use a repository over HTTPS
do_install_packages() {
sudo apt-get install --assume-yes \
     apt-transport-https \
     ca-certificates \
     curl \
     gnupg2 \
     software-properties-common
}	 
	 
# Add Docker’s official GPG key
do_add_docker_gpg_key () {
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
}

# Verify that you now have the key with the fingerprint 9DC8 5822 9FC7 DD38 854A E2D8 8D81 803C 0EBF CD88, by searching for the last 8 characters of the fingerprint.
do_check_docker_fingerprint () {

FINGERPRINT=0EBFCD88

if [[ ! $(apt-key fingerprint $FINGERPRINT) ]] ; then
	echo "docker gpg fingerprint $FINGERPRINT not found"
	exit 1
fi
}

# Install stable repository
do_install_stable_repository() {
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
}

# Install Docker CE
do_install_docker_CE () {
sudo apt-get update
sudo apt-get --assume-yes install docker-ce

}


# Main
main () {
do_install_packages() 
do_add_docker_gpg_key ()
do_check_docker_fingerprint ()
do_install_stable_repository() 
do_install_docker_CE ()
}

main
