#!/usr/bin/env bash
#
# Post-installation Configuration Scripts
#
# Common Debian based host tasks
# - Install base packages

#!/bin/bash
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>log_install_basic_packages.out 2>&1

do_upgrade () {
  apt-get --assume-yes update
  apt-get --assume-yes upgrade
  apt-get --assume-yes dist-upgrade
}


install_base_packages () {
  apt-get --assume-yes install sudo
}

main () {
	install_base_packages
}

main